language: node_js
node_js:
  - "7"
install:
  - npm install -g codecov istanbul
script:
  - npm install
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY